#!/usr/bin/env python3
"""
chart_converter.py — JSON chart source → C++ NoteChart translation unit
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Hardened version: fixes template paths, sorting asset safety, and alignment checks.
"""

import json
import sys
import os
from dataclasses import dataclass, field

# ── Constants mirroring the C++ engine ────────────────────────────────────────
TIMELINE_MAX     = 0xFFFF
MAX_NOTES        = 512  # MAX_NOTES_PER_CHART from NoteChart.h
LANE_MAP: dict[str, int] = {'L': 0, 'R': 1, 'U': 2, 'D': 3}
FLAG_MAP: dict[str, int] = {
    'mine':   0x01,
    'fake':   0x02,
    'accent': 0x04,
}
DEFAULT_METER_NUMERATOR = 4  # 4/4 time

@dataclass(order=True)
class NoteRow:
    """One emitted C++ Note struct, fully resolved to integer fields."""
    sort_index: tuple = field(init=False, repr=False)
    timeline:    int  = 0       # uint16_t Q8.8
    hold_length: int  = 0       # uint16_t Q8.8, 0 = tap
    lane:        int  = 0       # uint8_t  0–3
    flags:       int  = 0       # uint8_t  bitmask
    source_time: str  = ""      # original time string, for error messages

    def __post_init__(self):
        self.sort_index = (self.timeline, self.lane)

class TickEncoder:
    def __init__(self, total_bars: int, meter_numerator: int = DEFAULT_METER_NUMERATOR):
        if 0x10000 % total_bars != 0:
            raise ValueError(
                f"total_bars={total_bars} does not evenly divide 0x10000. "
                f"Chart bars must be a power-of-two for exact tick mapping."
            )
        self.ticks_per_bar  = 0x10000 // total_bars
        self.ticks_per_beat = self.ticks_per_bar // meter_numerator
        self.ticks_per_16th = self.ticks_per_beat // 4

    def encode(self, time_str: str) -> int:
        parts = time_str.strip().split(':')
        if len(parts) != 3:
            raise ValueError(f"Time string '{time_str}' must be 'bar:beat:sixteenth'")
        try:
            bar, beat, sixteenth = int(parts[0]), int(parts[1]), int(parts[2])
        except ValueError:
            raise ValueError(f"Time string '{time_str}' contains non-integer components.")

        tick = (bar * self.ticks_per_bar) + (beat * self.ticks_per_beat) + (sixteenth * self.ticks_per_16th)

        if not (0 <= tick <= TIMELINE_MAX):
            raise ValueError(f"Time string '{time_str}' resolves to tick 0x{tick:04X} (out of bounds).")
        return tick

    def encode_duration(self, duration_str: str) -> int:
        parts = duration_str.strip().split(':')
        if len(parts) != 3:
            raise ValueError(f"Hold duration '{duration_str}' must be 'bar:beat:sixteenth'.")
        try:
            bar, beat, sixteenth = int(parts[0]), int(parts[1]), int(parts[2])
        except ValueError:
            raise ValueError(f"Hold duration '{duration_str}' contains non-integer components.")
        return (bar * self.ticks_per_bar) + (beat * self.ticks_per_beat) + (sixteenth * self.ticks_per_16th)

def assemble_flags(flag_list: list[str]) -> int:
    result = 0
    for name in flag_list:
        if name not in FLAG_MAP:
            raise ValueError(f"Unknown flag '{name}'. Valid flags: {list(FLAG_MAP.keys())}")
        result |= FLAG_MAP[name]
    return result

def expand_note(entry: dict, encoder: TickEncoder) -> list[NoteRow]:
    time_str  = entry.get("time", "")
    lane_str  = entry.get("lane", "")
    hold_str  = entry.get("hold", "0:0:0")
    flag_list = entry.get("flags", [])

    if not time_str or not lane_str:
        raise ValueError(f"Note entry missing time or lane fields: {entry}")
    if len(set(lane_str)) != len(lane_str):
        raise ValueError(f"Lane string '{lane_str}' contains duplicate characters.")

    for ch in lane_str:
        if ch not in LANE_MAP:
            raise ValueError(f"Unknown lane character '{ch}' in '{lane_str}'.")

    timeline    = encoder.encode(time_str)
    hold_length = encoder.encode_duration(hold_str)
    flags       = assemble_flags(flag_list)

    if hold_length > 0 and (timeline + hold_length) > TIMELINE_MAX:
        print(f"  WARNING: Hold at '{time_str}' overflows 0xFFFF boundary. Clamping will apply.", file=sys.stderr)

    rows = []
    for ch in lane_str:
        rows.append(NoteRow(
            timeline    = timeline,
            hold_length = hold_length,
            lane        = LANE_MAP[ch],
            flags       = flags,
            source_time = time_str
        ))
    return rows

# ── Safe code generation templates (Fixed to align with NoteChart.h fields) ───

CPP_HEADER_TEMPLATE = """\
// {filename}
// AUTO-GENERATED by chart_converter.py — DO NOT EDIT BY HAND.
// Source: {source_json}
// Song ID: {song_id}  |  BPM hint: {bpm}  |  Bars: {bars}  |  Notes: {note_count}
//
// Timeline encoding: Q8.8 uint16_t across 0x0000–0xFFFF ({bars} bars)
//    ticks_per_bar  = 0x{ticks_per_bar:04X}
//    ticks_per_beat = 0x{ticks_per_beat:04X}
//    ticks_per_16th = 0x{ticks_per_16th:04X}

#include "charts/SongIndex.h"

namespace Engine::Charts {{

static const Note kSong{song_id_padded}_Notes[] = {{
//    {{ timeline, holdLength, lane, flags }}
"""

# FIXED: Field initialization ordering matches struct Note memory packing layout exactly
# FIXED: Matches the 4-byte structure initialization precisely
CPP_NOTE_ROW = "    {{ 0x{timeline:04X}, {lane}, 0x{flags:02X} }},  // {comment}\n"

CPP_FOOTER_TEMPLATE = """\
}};

constexpr uint16_t kSong{song_id_padded}_NoteCount = static_cast<uint16_t>(sizeof(kSong{song_id_padded}_Notes) / sizeof(Note));

static_assert(
    kSong{song_id_padded}_NoteCount > 0,
    "Song{song_id_padded}: Note chart cannot be empty."
);

static_assert(
    kSong{song_id_padded}_NoteCount <= {max_notes},
    "Song{song_id_padded}: note count exceeds MAX_NOTES_PER_CHART pool bounds."
);

static_assert(
    kSong{song_id_padded}_Notes[kSong{song_id_padded}_NoteCount - 1].timeline >= kSong{song_id_padded}_Notes[0].timeline,
    "Song{song_id_padded}: Chart end boundary points backwards in time."
);

// High-portability structural sequence initialization matching NoteChart.h
const NoteChart kSong{song_id_padded}_Chart = {{
    {song_id},                       // songId
    kSong{song_id_padded}_NoteCount,      // noteCount
    {bpm},                     // tempoBPM
    kSong{song_id_padded}_Notes // notes array pointer reference
}};

}} // namespace Engine::Charts
"""

LANE_NAMES = {0: 'L', 1: 'R', 2: 'U', 3: 'D'}

def emit_cpp(rows: list[NoteRow], song_id: int, bpm: int, bars: int, encoder: TickEncoder, source_json: str, output_path: str) -> None:
    song_id_padded = f"{song_id:02d}"
    filename       = os.path.basename(output_path)
    note_count     = len(rows)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(CPP_HEADER_TEMPLATE.format(
            filename       = filename,
            source_json    = os.path.basename(source_json),
            song_id        = song_id,
            song_id_padded = song_id_padded,
            bpm            = bpm,
            bars           = bars,
            note_count     = note_count,
            ticks_per_bar  = encoder.ticks_per_bar,
            ticks_per_beat = encoder.ticks_per_beat,
            ticks_per_16th = encoder.ticks_per_16th,
        ))

        for row in rows:
            lane_char = LANE_NAMES[row.lane]
            hold_type = f"hold {row.hold_length:#06x}" if row.hold_length else "tap"
            comment   = f"t={row.source_time} lane={lane_char} {hold_type}"

            f.write(CPP_NOTE_ROW.format(
                timeline = row.timeline,
                hold     = row.hold_length,
                lane     = row.lane,
                flags    = row.flags,
                comment  = comment,
            ))

        f.write(CPP_FOOTER_TEMPLATE.format(
            song_id_padded = song_id_padded,
            song_id        = song_id,
            bpm            = bpm,
            max_notes      = MAX_NOTES,
        ))

def convert(input_json: str, song_id: int, output_cpp: str) -> None:
    print(f"chart_converter: reading '{input_json}'")
    with open(input_json, 'r', encoding='utf-8') as f:
        chart = json.load(f)

    bpm    = int(chart.get("bpm", 120))
    bars   = int(chart.get("bars", 16))
    meter  = int(chart.get("meter", 4))
    notes  = chart.get("notes", [])

    encoder = TickEncoder(total_bars=bars, meter_numerator=meter)

    all_rows: list[NoteRow] = []
    for i, entry in enumerate(notes):
        try:
            all_rows.extend(expand_note(entry, encoder))
        except ValueError as exc:
            print(f"  ERROR in note[{i}]: {exc}", file=sys.stderr)
            sys.exit(1)

    if len(all_rows) > MAX_NOTES:
        print(f"  ERROR: {len(all_rows)} notes exceeds ceiling limit.", file=
